# Server settings
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8085
    # HTTP请求和响应头的最大量，以字节为单位，默认值为4096字节,超过此长度的部分不予处理,一般8K。解决java.io.EOFException: null问题
#    max-http-header-size: 8192
#    use-forward-headers: true
#    compression:
#        enabled: true
#        min-response-size: 1024
#        mime-types: text/plain,text/css,text/xml,text/javascript,application/json,application/javascript,application/xml,application/xml+rss,application/x-javascript,application/x-httpd-php,image/jpeg,image/gif,image/png

spring:
#    datasource:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/irmp?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
#        username: root
#        password: 123456
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    # thymeleaf 模板引擎
    thymeleaf:
        cache: false
        prefix: classpath:/templates/
        suffix: .html
        mode: LEGACYHTML5
#        mode: HTML5
        encoding: UTF-8
        content-type: text/html
    resources: # 指定静态资源的路径
        static-locations: classpath:/static/,classpath:/templates/

# MyBatis
#mybatis:
#    mapper-locations: classpath:/mybatis/*.xml
# Mybatis配置
mybatis:
    configLocation: classpath:mybatis.xml

# 分页配置
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql

#LOGGING
logging:
  config:
    classpath: log4j2-spring.xml
